### PR TITLE
Fix STU3 URLs

### PR DESCRIPTION
**Pull request by ahatherly**
Hi,
I've updated the resources in quite a few places to correct the STU3 URLs, and also put the actual CodeSystem URLs in - hopefully I've done it all right!
Adam.

### CODE REVIEW

**Comment by IOPS-DEV** [comment]
Hi Adam,
Couple of things to mention. First, my develop branch was way out of date. I'd gone a bit rouge and updated changes directly on gh-pages branch rather than develop.  That said, the problems you fixed still existed on gh-pages. I'll spend some time this morning and get git updated and sync'd up, and make sure I only work on develop branch and merge into gh-pages from now on.

**Review by dxh73 — CHANGES_REQUESTED** [review]
url for CodeSystem 
https://fhir.nhs.uk/STU3/opt-out-source-codesystem-1 with no /CodeSystem/ part. 
Removal of<Valueset> element in the CodeSystem. 

Spine-OperationOutcome-1 has been removed as it's no longer required.

New example has been created called Consent-Example-1 to replace previous one.

**Comment by dxh73** [comment]
Hi Adam, 

Develop and gh-pages are now sync'd back up. This will have changed the codesystems, valuesets and example. The url structure for codesystem I've left the way we had it, but that's not to say it's the correct way (we're still learning about STU3 changes).

**Comment by ahatherly** [comment]
Cool – sorry if I caused issues for you ☺

Adam.


Adam Hatherly
Senior Technical Architect
Domain D - Interoperability
NHS Digital

adam.hatherly@nhs.net<mailto:adam.hatherly@nhs.net>
0113 397 4164
07920 861 737
www.digital.nhs.uk<http://www.digital.nhs.uk/>
@NHSDigital

General enquiries: 0300 303 5678
enquiries@nhsdigital.nhs.uk<mailto:enquiries@nhsdigital.nhs.uk>

**Comment by dxh73** [comment]
Hi Adam,
No probs, just the opposite. It's highlighted issues within CS, VS and the example that I'd missed, which shows the importance of a review.  I also need to get into the habit of working with git in the right way. A few lessons learned in the project.

**Pull request closed without merging**
